joint_names: [right_arm_1_joint, right_arm_2_joint, right_arm_3_joint, right_arm_4_joint, right_arm_5_joint, right_arm_6_joint, right_arm_7_joint]

# linear velocity limit [m/s] 
v_limit: 0.15  

# angular velocity limit [rad/s]
w_limit: 0.5 